export const DICOM_SEARCH_REQUESTED_ACTION = 'DICOM_SEARCH_REQUESTED_ACTION';
export const DICOM_SEARCH_SUCCEEDED_ACTION = 'DICOM_SEARCH_SUCCEEDED_ACTION';
export const DICOM_SEARCH_FAILED_ACTION = 'DICOM_SEARCH_FAILED_ACTION';

export const USER_LOGIN_ACTION_TYPE = 'user/login';
export const USER_LOGOUT_ACTION_TYPE = 'user/logout';
export const FETCH_USER_ACTION_TYPE = 'user/list';
export const FETCH_USER_LIST_SUCCESS_TYPE = 'userList/success';

export const TOKEN_FETCH_SUCCEEDED_ACTION = 'TOKEN_FETCH_SUCCEEDED_ACTION';
export const TOKEN_FETCH_FAILED_ACTION = 'TOKEN_FETCH_FAILED_ACTION';
export const TOKEN_FETCH_REQUESTED_ACTION = 'TOKEN_FETCH_REQUESTED_ACTION';