/* eslint-disable @typescript-eslint/camelcase */
import { ExamIndexListI } from "_constants/interface";

export default [
  {
    id: "1",
    modality: "CT",
    patient_name: "123",
    created_at: new Date(),
    desc: "",
    patient_id: "1_1",
    institution_name: "hhh",
    study_date: "2019-01-01",
    thumbnail: "",
  },
  {
    id: "2",
    modality: "AAA",
    patient_name: "456",
    created_at: new Date(),
    desc: "hhhhh",
    patient_id: "1_2",
    institution_name: "sssss",
    study_date: "2019-11-23",
    thumbnail: "http://m.imeitou.com/uploads/allimg/2018082311/qdtnl3ajzuf.jpg",
  },
  {
    id: "4",
    modality: "AAA1",
    patient_name: "456",
    created_at: new Date(),
    desc: "hhhhh",
    patient_id: "1_3",
    institution_name: "sssss",
    study_date: "2019-11-23",
    thumbnail: "http://m.imeitou.com/uploads/allimg/2018082311/qdtnl3ajzuf.jpg",
  },
  {
    id: "3",
    modality: "AAA1",
    patient_name: "42256",
    created_at: new Date(),
    desc: "hhhhh",
    patient_id: "1_4",
    institution_name: "sssss",
    study_date: "2019-11-23",
    thumbnail: "http://m.imeitou.com/uploads/allimg/2018082311/qdtnl3ajzuf.jpg",
  },
  {
    id: "5",
    modality: "CT",
    patient_name: "123",
    created_at: new Date(),
    desc: "",
    patient_id: "1_1",
    institution_name: "hhh",
    study_date: "2019-01-01",
    thumbnail: "",
  },
  {
    id: "6",
    modality: "AAA",
    patient_name: "456",
    created_at: new Date(),
    desc: "hhhhh",
    patient_id: "1_2",
    institution_name: "sssss",
    study_date: "2019-11-23",
    thumbnail: "http://m.imeitou.com/uploads/allimg/2018082311/qdtnl3ajzuf.jpg",
  },
  {
    id: "7",
    modality: "AAA1",
    patient_name: "456",
    created_at: new Date(),
    desc: "hhhhh",
    patient_id: "1_3",
    institution_name: "sssss",
    study_date: "2019-11-23",
    thumbnail: "http://m.imeitou.com/uploads/allimg/2018082311/qdtnl3ajzuf.jpg",
  },
] as ExamIndexListI[];
